### ISSUE TITLE
VSCODE + PlatformIO compiling ERROR...error: void value not ignored as it ought to be

### ISSUE THREAD

**Issue by sakunamary** [myTonino/Tonino-Firmware#3]
I have try to make a Tonino meter ,I try to compiling in vscode + platformIO , and some errors reported as following :

Compiling .pio\build\arduino_nano_win10\FrameworkArduino\HardwareSerial0.cpp.o
lib\Tonino\tonino_serial.cpp: In static member function 'static boolean ToninoSerial::checkCommands()':
lib\Tonino\tonino_serial.cpp:66:28: error: void value not ignored as it ought to be
    return _sCmd.readSerial();

I try to compile in ArduinoIDE(version:1.8.19 ), errors reported as vscode....

Please help me to fix it .Thank you guys!

**Comment by sakunamary** [comment]
I have found what happened , the issue is OK now.
